### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by alexkushnarov** [hamedbaatour/angularfire-lite#32]
Hi, can you help me pls?
I'm facing the same issue with FB - https://github.com/angular/angularfire2/issues/1575.
I'm wondering how to set timestampsInSnapshots: true to angularfire-lite config to get rid of the console error.

**Comment by hamedbaatour** [comment]
just released a fix on AFL 6.0.1 which sets automatically for you `timestampsInSnapshots: true`

**Comment by alexkushnarov** [comment]
Thanks @hamedbaatour, but after I updated angularfire-lite from 5.2.0 to 6.0.1 it started to throw an error.
on this line `import { AngularFireLite } from 'angularfire-lite';`

ERROR in src/app/app.module.ts(12,33): error TS2307: Cannot find module 'angularfire-lite'.

but I see angularfire-lite in my node_modules (image attached)
<img width="300" alt="screen shot 2018-09-13 at 3 49 50 pm" src="https://user-images.githubusercontent.com/13591263/45489390-c983a900-b76c-11e8-89dd-ddadd9c2f62b.png">



P.S My angular version is 5

**Comment by alexkushnarov** [comment]
Also I've just checked the v6.0.0 and it see the module, but also trhow error on app compile
ERROR in node_modules/angularfire-lite/messaging/messaging.service.d.ts(3,35): error TS2307: Cannot find module '@firebase/messaging-types'.

**Comment by hamedbaatour** [comment]
can you completely delete your node_modules folder and reinstall angularfire-lite v6.0.2 If you are still facing the same error can you share a reproduction of the issue?

**Comment by alexkushnarov** [comment]
ok I've updated "angularfire-lite" to "^6.0.2", and "firebase" to "^5.4.2"

I did `rm -rf node_modules/ && npm cache clean -f && npm i && ng serve` and on ng serve I see 

ERROR in node_modules/angularfire-lite/messaging/messaging.service.d.ts(3,35): error TS2307: Cannot find module '@firebase/messaging-types'.

but after I did `npm i --save-dev @firebase/messaging-types` it becomes ok.

Thanks for the fix, I appreciate that.

**Comment by alexkushnarov** [comment]
Hi @hamedbaatour 

Can you help me pls?

I've updated firebase to ^5.8.0 and seeing this error

> @firebase/firestore: Firestore (5.8.0): 
>   The timestampsInSnapshots setting now defaults to true and you no
>   longer need to explicitly set it. In a future release, the setting
>   will be removed entirely and so it is recommended that you remove it
>   from your firestore.settings() call now.

can you pls get rid of timestampsInSnapshots: true which you set previously

**Comment by ev45ive** [comment]
./node_modules/@angular/fire/firestore/firestore.js
```typescript
export var DefaultFirestoreSettings = { 
// THIS NEEDS TO BE REMOVED:
    timestampsInSnapshots: true 
};
export function associateQuery(collectionRef, queryFn) {
    if (queryFn === void 0) { queryFn = function (ref) { return ref; }; }
    var query = queryFn(collectionRef);
    var ref = collectionRef;
    return { query: query, ref: ref };
}
var AngularFirestore = (function () {
    function AngularFirestore(options, nameOrConfig, shouldEnablePersistence, settings, platformId, zone, persistenceSettings) {
        var _this = this;
        this.scheduler = new FirebaseZoneScheduler(zone, platformId);
        this.firestore = zone.runOutsideAngular(function () {
            var app = _firebaseAppFactory(options, nameOrConfig);
            var firestore = app.firestore();
            firestore.settings(settings || DefaultFirestoreSettings);
            return firestore;
        });
```
@alexkushnarov In the mean time you can override settings in your app.module.ts:
```
...
  providers: [
    {
      provide: FirestoreSettingsToken,
      useValue: {
        timestampsInSnapshots: undefined
      }
    }
  ],
```

**Comment by Sagar2493** [comment]
I just ran this command : npm install --save angularfire-lite . It worked for me. Also installed latest version of "angularfire2" and "firebase".
In my package.json file its looks like:
"angularfire-lite": "^6.0.3",
 "angularfire2": "^5.4.2",
 "firebase": "4.8.0",
